# Willkommensnachricht, wenn der Spieler den Server betritt
Welcome_message: Willkommen %playername%~
# Rundenendnachricht
Round_end_info: Die Runde ist vorbei! Geh nicht, wir sehen uns beim nächsten Spiel ヾ(￣▽￣)~
# Die Nachricht, die Spieler erhalten, wenn freundlicher Schaden aktiviert ist
f_f_message: <align=center><voffset=28em> <color=#F6511D> ~Freundlicher Schaden ist aktiviert~ </color></voffset></align>
# Server-Broadcast-Text
auto_server_message_text: Server-Broadcast
# Ausgabetext des Administratormonitors
admin_log: '%Nickname% um %Time% |. ​​Verwendeter Befehl: %Command% |.
# Der Administrator überwacht die Befehlsübertragung
admin_log_broadcast: '<size=30>[<color=red>Management Behavior Monitoring Output Record</color>] <%Nickname%> hat gerade den Befehl verwendet: %Command%</size>'
# Zeigt die verbleibende Zeit bis zum Start und den Serverstatus an
title_text: <size=50><color=#F0FF00><b>Warten auf Spieler, {Sekunden</b></color></size>
# Text, der die Anzahl der Spieler anzeigt
player_count_text: <size=40><color=#FFA600><i>{players}</i></color></size>
# Meldung wird angezeigt, wenn die Lobby gesperrt ist
server_pause_text: Der Server wurde angehalten
#Nachricht in der zweiten Zeile
second_left_text: Noch {Sekunden} übrig
#Mehrere Nachrichtenzeilen
seconds_left_text: Noch {Sekunden} übrig
# Meldung wird angezeigt, wenn die Runde beginnt
Round_start_text: Rundenanfang
# Die Meldung, die angezeigt wird, wenn der Server einem Spieler beitritt
player_join_text: Spieler tritt bei
# Die Meldung wird angezeigt, wenn mehrere Spieler dem Server beitreten
player_join_text: Spieler treten bei
# Ankündigung wird angezeigt, wenn die Wachen meutern
Guard_mutiny_broadcast: <size=60><color=#ff0000ff>[Warnung]</color>Die Wachen dieser Einrichtung wurden von der Chaos Insurgency zur Rebellion angestiftet</size>
# Ankündigungen, die von Wachen für Eliteteams angezeigt werden
elite_guard_broadcast: <size=60><color=#00ffffff>[Hinweis]</color>Die Wachen dieser Einrichtung sind Elite-Mitglieder des Neunschwänzigen Fuchses und ihre Sicherheitsstärke wurde erheblich erhöht</size>
# Titel der Beobachtungsliste
watch_list_title: <align=right><size=45%><color=(COLOR)><b>Beobachter ((COUNT)):</b></color></size></align>
# Watchlist-Format
Namen: <align=right><size=45%><color=(COLOR)><br>(NAME)</color></size></align>
#DNT-Erinnerung
d_n_t_warning: Sie haben DNT aktiviert. Bitte schalten Sie es aus, da sonst einige Plug-Ins nicht ordnungsgemäß funktionieren.
# Ursache der umgekehrten Verletzung durch SCP-073
s_c_p073_damage_reason: SCP073 Rückwärtsschaden
# SCP-029FluchteinrichtungHinweis
s_c_p029_escape_hint: Entkommen Sie erfolgreich aus der Einrichtung, werden Sie zum Chaos und erhalten Sie ein Vermächtnis von der Chaos Insurgency.
#SCP-703FluchteinrichtungHinweis
s_c_p703_escape_hint: Entkomme erfolgreich aus der Einrichtung und werde ein Experte für die Eindämmung von Neunschwänzigen Füchsen, erhalte 3x
# Skynet Mobile Task Force Cassie Broadcast
skynet_cassie: Die mobilen Einsatzkräfte Kappa-10 und Mu-7 mit dem Codenamen Skynet haben die Anlage betreten. Sie werden Dancer One dabei helfen, SCP-079 einzudämmen. Allen überlebenden Mitarbeitern wird empfohlen, die Standard-Evakuierungsprotokolle zu befolgen, bis das MTF-Team an Ihrem Standort eintrifft. Derzeit sind %SCPNum% SCPs übrig
# Rekrutierungsübertragung der Skynet Mobile Task Force
skynet_private_broadcast: <size=70><color=#0051FF>Sie sind ein Rekrut der Mobile Task Force-Skynet</color></size>
# Skynet Mobile Task Force rekrutiert benutzerdefinierte Informationen
skynet_private_custom_info: Skynet-Rekrut
# Übertragung der Skynet Mobile Task Force Sgt
skynet_sergeant_broadcast: <size=70><color=#0051FF>Sie sind Sergeant der Mobile Task Force-Skynet</color></size>
# Skynet Mobile Task Force rekrutiert benutzerdefinierte Informationen
skynet_sergeant_custom_info: Skynet-Sergeant
# Skynet Mobile Task Force Commander-Übertragung
skynet_captain_broadcast: <size=70><color=#0051FF>Sie sind der Kommandeur der Mobile Task Force-Skynet</color></size>
# Benutzerdefinierte Informationen zum Skynet Mobile Task Force Commander
skynet_captain_custom_info: Skynet-Kommandant
#Siehe No Evil Mobile Task Force Cassie Broadcast
see_no_evil_cassie: Die mobile Task Force Eta-10 mit dem Codenamen „See No Evil“ hat die Einrichtung betreten. Sie wird dabei helfen, SCP-096 einzudämmen. Es wird empfohlen, dass alle überlebenden Mitarbeiter Standard-Evakuierungsprotokolle umsetzen, bis das MTF-Team an Ihrem Standort eintrifft % SCPs übrig.
#Look No Evil Mobile Task Force-Rekrutensendung
see_no_evil_private_broadcast: <size=70><color=#0051FF>Sie sind eine mobile Task Force – sehen Sie keinen bösen Rekruten</color></size>
# Sehen Sie keine bösen Mobile Task Force-Rekrutierungsinformationen
see_no_evil_private_custom_info: Siehe No Evil Recruit
#Look No Evil-Übertragung von Mobile Task Force Sgt.
see_no_evil_sergeant_broadcast: <size=70><color=#0051FF>Sie sind Mobile Task Force – Siehe No Evil Sergeant</color></size>
# Sehen Sie keine bösen Mobile Task Force-Rekrutierungsinformationen
see_no_evil_sergeant_custom_info: Sehen Sie keinen bösen Sergeant
#Look No Evil-Übertragung des Kommandanten der Mobile Task Force
see_no_evil_captain_broadcast: <size=70><color=#0051FF>Du bist der Mobile Task Force – See No Evil Commander</color></size>
# Keine böse benutzerdefinierte Nachricht des Kommandanten der Mobile Task Force sehen
see_no_evil_captain_custom_info: Sehe keinen bösen Kommandanten
#Sonderzeichen sind im Cassie-Suffix enthalten
special_role_contain_cassie: Erfolgreich beseitigt, der genaue Grund ist unbekannt
Name des #Chaos-Anführers
chaos_leader_role_name: Chaos-Anführer
Aktualisierungsübertragung des #Chaos-Anführers
chaos_leader_spawn_broadcast: <size=80><color=#00ff00ff>Du bist der Anführer der Chaos Insurgency</color></size>
#ChaosLeaderDeathCassie
chaos_leader_death_cassie: Chaos-Anführer stirbt
# SCP-2936-1 Aktualisierungsübertragung
s_c_p29361_spawn_broadcast: <size=70>Du bist <color=red>SCP-2936-1 Riesiger deutscher Roboter</color></size>
# SCP-073 Abel Refresh Broadcast
s_c_p073_abel_spawn_broadcast: Du bist <color=green>SCP-073 Abel</color>
# SCP-073 Übertragung aktualisieren
s_c_p073_cain_spawn_broadcast: Du bist <color=green>SCP-073 Cain</color>
# SCP-703 Aktualisierungsübertragung
s_c_p703_spawn_broadcast: <size=80><color=#00ffffff>Du bist SCP-703</color></size>
#SCP-703 Fertigkeitseinführung
s_c_p703_skill_introduction: <align=center><voffset=28em><size=70><color=#00ffffff>Du erhältst jedes Mal zufällige Gegenstände</color></size></voffset></align>
# SCP-703 Hinweis-Eingabeaufforderung zum Erhalten des Gegenstands
s_c_p703_received_item_hint: Einen Artikel erhalten
# SCP-029 Übertragung aktualisieren
s_c_p029_spawn_broadcast: <size=60><color=#ff0000ff>Du bist SCP-029 „Tochter des Schattens“</color></size>
#SCP-029 Fertigkeitseinführung
s_c_p029_skill_introduction: <voffset=28em><size=40><color=#ff0000ff>Töte jeden, dem du feindlich gesinnt bist</color></size></voffset>
# SCP-347 Übertragung aktualisieren
s_c_p347_spawn_broadcast: Du bist <color=red>SCP-347 Invisible Woman</color>
# SCP-1093 Übertragung aktualisieren
s_c_p1093_spawn_broadcast: Du bist <color=yellow>SCP-1093 Spawn</color>
#SCP-1093 Fertigkeitseinführung
s_c_p1093_skill_introduction: >-
 Beleuchtet kontinuierlich einen nahen 5-Meter-Bereich und wirkt sich auf Personen in einem nahen 1-Meter-Bereich aus, so dass sie Strahlungsschaden erleiden (pro Sekunde wird 1 HP abgezogen).
 
 Dein Kopf scheint nichts zu sein, also kann niemand deinem Kopf etwas anhaben.
# Wachhauptmann aktualisiert die Übertragung
Guard_captain_spawn_broadcast: <size=60><color=#E5DADA>Du bist der Sicherheitskapitän</color></size>
# SCP-191 Aktualisierungsübertragung
s_c_p191_spawn_broadcast: Du wurdest zum <color=red>SCP-191 Mechanical Girl</color>
#SCP-191 Fertigkeitseinführung
s_c_p191_skill_introduction: Aufgrund Ihrer Körpermodifikationen sind Sie äußerst widerstandsfähig gegen andere Schäden als elektromagnetische und explosive Schäden.
# SCP-191-Leistungsanzeige
s_c_p191_battery_hint_show: <align=right><size=60><b>Ihre aktuell verbleibende Akkukapazität: <color=yellow>%Battery%An</color></size></b></align>
# SCP-1056-Reduktionsgerät nimmt Hinweis auf
s_c_p1056_pickup_hint: Du hast den <color=red>SCP-1056</color>-Reduzierer aufgehoben!
# SCP-1056-Reduktionsgerät mit Hinweis
s_c_p1056_used_hint: Boom! Du wirst kleiner!!!
#SCP-1068 Hinweis zum Aufsammeln harmloser Atombomben
s_c_p1068_pickup_hint: Du hast die <color=red>SCP-1068</color> harmlose Atombombe aufgehoben!
# SCP-1056 Übertragung über den Einsatz harmloser Atombomben
s_c_p1068_used_broadcast: Jemand hat <color=red>SCP-1068</color>, eine harmlose Atombombe, eingesetzt!
